[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = custom_partitions.csv
; Правильный формат записи флагов для принудительного сброса:
upload_flags =
    --before=default_reset
    --after=hard_reset
